//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.27 at 08:32:58 PM CDT 
//


package org.united.airvision.models.amosResponse;

import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import org.springframework.stereotype.Component;

import java.io.Serializable;


@Component
@JacksonXmlRootElement(localName = "AircraftKey")
public class AircraftKey implements Serializable {

    @JacksonXmlProperty(localName = "AircraftID", isAttribute = true)
    protected String aircraftID;
    @JacksonXmlProperty(localName = "AircraftTypeCode", isAttribute = true)
    protected String aircraftTypeCode;

    public String getAircraftID() {
        return aircraftID;
    }
    public void setAircraftID(String value) {
        this.aircraftID = value;
    }

    public String getAircraftTypeCode() {
        return aircraftTypeCode;
    }

    public void setAircraftTypeCode(String value) {
        this.aircraftTypeCode = value;
    }
}
