//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.27 at 08:32:58 PM CDT 
//


package org.united.airvision.models.amosResponse;

import java.io.Serializable;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;

import org.springframework.stereotype.Component;

@Component
@JacksonXmlRootElement(localName = "AMOSFlightDetailsResponse",namespace="http://airserv.com/Ops-I-002/AMOSDetailResponse/MAY2005")
public class AMOSFlightDetailsResponse implements Serializable {
    @JacksonXmlProperty(localName = "AircraftKey")
    protected AircraftKey aircraftKey;
    @JacksonXmlProperty(localName="Cabin")
    @JacksonXmlElementWrapper(useWrapping = false)
    protected List<Cabin> cabin;
    @JacksonXmlProperty(localName = "AirlineCode", isAttribute = true)
    protected String airlineCode;
    @JacksonXmlProperty(localName="FlightNumber", isAttribute = true)
    protected String flightNumber;
    @JacksonXmlProperty(localName = "OperationalSuffix", isAttribute = true)
    protected String operationalSuffix;
    @JacksonXmlProperty(localName = "FlightDate", isAttribute = true)
    protected String flightDate;
    @JacksonXmlProperty(localName = "DepartureStationCode", isAttribute = true)
    protected String departureStationCode;
    @JacksonXmlProperty(localName = "ArrivalStationCode", isAttribute = true)
    protected String arrivalStationCode;
    @JacksonXmlProperty(localName = "QueryPeriod", isAttribute = true)
    protected BigInteger queryPeriod;
    @JacksonXmlProperty(localName = "DepartureGate", isAttribute=true)
    protected String departureGate;
    @JacksonXmlProperty(localName = "FlightStatus", isAttribute = true)
    protected String flightStatus;
    @JacksonXmlProperty(localName = "CancelTime", isAttribute = true)
    protected String cancelTime;
    @JacksonXmlProperty(localName = "EstimatedDepartureTime", isAttribute=true)
    protected String estimatedDepartureTime;
    @JacksonXmlProperty(localName = "ErrorResponse", isAttribute=true)
    protected String errorResponse;
    @JacksonXmlProperty(localName = "BoardingAirlineCode" ,isAttribute=true)
    protected String boardingAirlineCode;
    @JacksonXmlProperty(localName = "BoardingFlightNumber", isAttribute=true)
    protected Integer boardingFlightNumber;
    @JacksonXmlProperty(localName = "BoardingOperationalSuffix", isAttribute=true)
    protected String boardingOperationalSuffix;
    @JacksonXmlProperty(localName = "BoardingFlightDate", isAttribute=true)
    protected String boardingFlightDate;
    @JacksonXmlProperty(localName = "BoardingDepartureStationCode", isAttribute = true)
    protected String boardingDepartureStationCode;
    @JacksonXmlProperty(localName = "BoardingArrivalStationCode", isAttribute=true)
    protected String boardingArrivalStationCode;
    @JacksonXmlProperty(localName = "BoardingFacilityStationCode", isAttribute=true)
    protected String boardingFacilityStationCode;
    @JacksonXmlProperty(localName = "BoardingFacilityTypeCode" ,isAttribute=true)
    protected String boardingFacilityTypeCode;
    @JacksonXmlProperty(localName = "BoardingFacilitySequenceNumber", isAttribute = true)
    protected Integer boardingFacilitySequenceNumber;

    public AircraftKey getAircraftKey() {
        return aircraftKey;
    }

    public void setAircraftKey(AircraftKey value) {
        this.aircraftKey = value;
    }

    public List<Cabin> getCabin() {
        if (cabin == null) {
            cabin = new ArrayList<Cabin>();
        }
        return this.cabin;
    }

    public void setCabin(List<Cabin> cabins){
        this.cabin=cabins;
    }

    public String getAirlineCode() {
        return airlineCode;
    }

    public void setAirlineCode(String value) {
        this.airlineCode = value;
    }
    public String getFlightNumber() {
        return flightNumber;
    }

    public void setFlightNumber(String value) {
        this.flightNumber = value;
    }

    public String getOperationalSuffix() {
        return operationalSuffix;
    }

    public void setOperationalSuffix(String value) {
        this.operationalSuffix = value;
    }


    public String getFlightDate() {
        return flightDate;
    }

    public void setFlightDate(String value) {
        this.flightDate = value;
    }
    public String getDepartureStationCode() {
        return departureStationCode;
    }

    public void setDepartureStationCode(String value) {
        this.departureStationCode = value;
    }

    public String getArrivalStationCode() {
        return arrivalStationCode;
    }

    public void setArrivalStationCode(String value) {
        this.arrivalStationCode = value;
    }

    public BigInteger getQueryPeriod() {
        return queryPeriod;
    }

    public void setQueryPeriod(BigInteger value) {
        this.queryPeriod = value;
    }

    public String getDepartureGate() {
        return departureGate;
    }

    public void setDepartureGate(String value) {
        this.departureGate = value;
    }

    public String getFlightStatus() {
        return flightStatus;
    }

    public void setFlightStatus(String value) {
        this.flightStatus = value;
    }

    public String getCancelTime() {
        return cancelTime;
    }

    public void setCancelTime(String value) {
        this.cancelTime = value;
    }

    public String getEstimatedDepartureTime() {
        return estimatedDepartureTime;
    }

    public void setEstimatedDepartureTime(String value) {
        this.estimatedDepartureTime = value;
    }

    public String getErrorResponse() {
        return errorResponse;
    }

    public void setErrorResponse(String value) {
        this.errorResponse = value;
    }

    public String getBoardingAirlineCode() {
        return boardingAirlineCode;
    }

    public void setBoardingAirlineCode(String value) {
        this.boardingAirlineCode = value;
    }

    public Integer getBoardingFlightNumber() {
        return boardingFlightNumber;
    }

    public void setBoardingFlightNumber(Integer value) {
        this.boardingFlightNumber = value;
    }

    public String getBoardingOperationalSuffix() {
        return boardingOperationalSuffix;
    }

    public void setBoardingOperationalSuffix(String value) {
        this.boardingOperationalSuffix = value;
    }

    public String getBoardingFlightDate() {
        return boardingFlightDate;
    }

    public void setBoardingFlightDate(String value) {
        this.boardingFlightDate = value;
    }

    public String getBoardingDepartureStationCode() {
        return boardingDepartureStationCode;
    }

    public void setBoardingDepartureStationCode(String value) {
        this.boardingDepartureStationCode = value;
    }

    public String getBoardingArrivalStationCode() {
        return boardingArrivalStationCode;
    }

    public void setBoardingArrivalStationCode(String value) {
        this.boardingArrivalStationCode = value;
    }

    public String getBoardingFacilityStationCode() {
        return boardingFacilityStationCode;
    }

    public void setBoardingFacilityStationCode(String value) {
        this.boardingFacilityStationCode = value;
    }

    public String getBoardingFacilityTypeCode() {
        return boardingFacilityTypeCode;
    }

    public void setBoardingFacilityTypeCode(String value) {
        this.boardingFacilityTypeCode = value;
    }

    public Integer getBoardingFacilitySequenceNumber() {
        return boardingFacilitySequenceNumber;
    }

    public void setBoardingFacilitySequenceNumber(Integer value) {
        this.boardingFacilitySequenceNumber = value;
    }

}
