//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.27 at 08:32:58 PM CDT 
//


package org.united.airvision.models.amosResponse;

import java.io.Serializable;
import java.math.BigInteger;

import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import org.springframework.stereotype.Component;


@Component
@JacksonXmlRootElement(localName = "CapacityBreakdown")
public class CapacityBreakdown implements Serializable {

    @JacksonXmlProperty(localName="Authorized", isAttribute = true)
    protected BigInteger authorized;
    @JacksonXmlProperty(localName="CrewRest", isAttribute = true)
    protected BigInteger crewRest;
    @JacksonXmlProperty(localName="WeightRestricted", isAttribute = true)
    protected BigInteger weightRestricted;
    @JacksonXmlProperty(localName="BlockedSeats", isAttribute = true)
    protected BigInteger blockedSeats;

    @JacksonXmlProperty(localName = "Other", isAttribute = true)
    protected BigInteger other;

    /**
     * Gets the value of the authorized property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getAuthorized() {
        return authorized;
    }

    /**
     * Sets the value of the authorized property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setAuthorized(BigInteger value) {
        this.authorized = value;
    }

    /**
     * Gets the value of the crewRest property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getCrewRest() {
        return crewRest;
    }

    /**
     * Sets the value of the crewRest property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setCrewRest(BigInteger value) {
        this.crewRest = value;
    }

    /**
     * Gets the value of the weightRestricted property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getWeightRestricted() {
        return weightRestricted;
    }

    /**
     * Sets the value of the weightRestricted property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setWeightRestricted(BigInteger value) {
        this.weightRestricted = value;
    }

    /**
     * Gets the value of the blockedSeats property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBlockedSeats() {
        return blockedSeats;
    }

    /**
     * Sets the value of the blockedSeats property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBlockedSeats(BigInteger value) {
        this.blockedSeats = value;
    }

    /**
     * Gets the value of the other property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getOther() {
        return other;
    }

    /**
     * Sets the value of the other property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setOther(BigInteger value) {
        this.other = value;
    }

}
