//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.27 at 08:32:58 PM CDT 
//


package org.united.airvision.models.amosResponse;

import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import org.springframework.stereotype.Component;

import java.io.Serializable;


@Component
@JacksonXmlRootElement(localName = "PreOrder")
public class PreOrder implements Serializable {


    @JacksonXmlProperty(localName="ServiceSequenceNumber")
    protected Integer serviceSequenceNumber;
    @JacksonXmlProperty(localName="SpecificationNumber")
    protected String specificationNumber;

    /**
     * Gets the value of the serviceSequenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getServiceSequenceNumber() {
        return serviceSequenceNumber;
    }

    /**
     * Sets the value of the serviceSequenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setServiceSequenceNumber(Integer value) {
        this.serviceSequenceNumber = value;
    }

    /**
     * Gets the value of the specificationNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecificationNumber() {
        return specificationNumber;
    }

    /**
     * Sets the value of the specificationNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecificationNumber(String value) {
        this.specificationNumber = value;
    }

}
