//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.27 at 08:32:58 PM CDT 
//


package org.united.airvision.models.amosResponse;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import org.springframework.stereotype.Component;

@Component
@JacksonXmlRootElement(localName = "SpecialMealInfo")
public class SpecialMealInfo implements Serializable {

    public void setSpecialMeal(List<SpecialMeal> specialMeal) {
        this.specialMeal = specialMeal;
    }


    @JacksonXmlProperty(localName = "SpecialMeal")
    @JacksonXmlElementWrapper(useWrapping = false)
    protected List<SpecialMeal> specialMeal;


    public List<SpecialMeal> getSpecialMeal() {
        if (specialMeal == null) {
            specialMeal = new ArrayList<SpecialMeal>();
        }
        return this.specialMeal;
    }

}
