//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.27 at 08:32:58 PM CDT 
//


package org.united.airvision.models.amosResponse;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlElementWrapper;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import org.springframework.stereotype.Component;


@Component
@JacksonXmlRootElement(localName="SpecialMeal")
public class SpecialMeal implements Serializable {


    @JacksonXmlProperty(localName="SpecialMealPassenger")
    protected SpecialMealPassenger specialMealPassenger;

    @JacksonXmlProperty(localName="PreOrder")
    @JacksonXmlElementWrapper(useWrapping = false)
    protected List<PreOrder> preOrder;
    @JacksonXmlProperty(localName="SpecialMealCode", isAttribute = true)
    protected String specialMealCode;
    @JacksonXmlProperty(localName="SpecialMealComment" ,isAttribute = true)
    protected String specialMealComment;
    @JacksonXmlProperty(localName="SpecialMealSeat", isAttribute = true)
    protected String specialMealSeat;

    /**
     * Gets the value of the specialMealPassenger property.
     * 
     * @return
     *     possible object is
     *     {@link SpecialMealPassenger }
     *     
     */
    public SpecialMealPassenger getSpecialMealPassenger() {
        return specialMealPassenger;
    }

    /**
     * Sets the value of the specialMealPassenger property.
     * 
     * @param value
     *     allowed object is
     *     {@link SpecialMealPassenger }
     *     
     */
    public void setSpecialMealPassenger(SpecialMealPassenger value) {
        this.specialMealPassenger = value;
    }

    /**
     * Gets the value of the preOrder property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the preOrder property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPreOrder().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PreOrder }
     * 
     * 
     */
    public List<PreOrder> getPreOrder() {
        if (preOrder == null) {
            preOrder = new ArrayList<PreOrder>();
        }
        return this.preOrder;
    }
    public void setPreOrder(List<PreOrder> preOrderList){
        this.preOrder=preOrderList;
    }

    /**
     * Gets the value of the specialMealCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialMealCode() {
        return specialMealCode;
    }

    /**
     * Sets the value of the specialMealCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialMealCode(String value) {
        this.specialMealCode = value;
    }

    /**
     * Gets the value of the specialMealComment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialMealComment() {
        return specialMealComment;
    }

    /**
     * Sets the value of the specialMealComment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialMealComment(String value) {
        this.specialMealComment = value;
    }

    /**
     * Gets the value of the specialMealSeat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSpecialMealSeat() {
        return specialMealSeat;
    }

    /**
     * Sets the value of the specialMealSeat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSpecialMealSeat(String value) {
        this.specialMealSeat = value;
    }

}
