//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.27 at 08:32:58 PM CDT 
//


package org.united.airvision.models.amosResponse;

import java.io.Serializable;
import java.math.BigInteger;

import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import org.springframework.stereotype.Component;


@Component
@JacksonXmlRootElement(localName="TotalCheckedInAndAccepted")
public class TotalCheckedInAndAccepted implements Serializable {

    @JacksonXmlProperty(localName = "TotalCheckedInAndAcceptedDetail")
    protected TotalCheckedInAndAcceptedDetail totalCheckedInAndAcceptedDetail;

    @JacksonXmlProperty(localName="Total", isAttribute = true)
    protected BigInteger total;


    public TotalCheckedInAndAcceptedDetail getTotalCheckedInAndAcceptedDetail() {
        return totalCheckedInAndAcceptedDetail;
    }


    public void setTotalCheckedInAndAcceptedDetail(TotalCheckedInAndAcceptedDetail value) {
        this.totalCheckedInAndAcceptedDetail = value;
    }


    public BigInteger getTotal() {
        return total;
    }


    public void setTotal(BigInteger value) {
        this.total = value;
    }

}
