//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.27 at 08:32:58 PM CDT 
//


package org.united.airvision.models.amosResponse;

import java.io.Serializable;
import java.math.BigInteger;

import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;
import org.springframework.stereotype.Component;


@Component
@JacksonXmlRootElement(localName = "TotalCheckedInAndAcceptedDetail")
public class TotalCheckedInAndAcceptedDetail implements Serializable {

    @JacksonXmlProperty(localName="LocalRevenueWithReservation", isAttribute = true)
    protected BigInteger localRevenueWithReservation;
    @JacksonXmlProperty(localName = "ThruRevenueWithReservation", isAttribute = true)
    protected BigInteger thruRevenueWithReservation;
    @JacksonXmlProperty(localName = "LocalRevenueStandby", isAttribute = true)
    protected BigInteger localRevenueStandby;
    @JacksonXmlProperty(localName = "ThruRevenueStandby", isAttribute = true)
    protected BigInteger thruRevenueStandby;
    @JacksonXmlProperty(localName = "LocalNonRevenueStandby", isAttribute = true)
    protected BigInteger localNonRevenueStandby;
    @JacksonXmlProperty(localName = "ThruNonRevenueStandby", isAttribute = true)
    protected BigInteger thruNonRevenueStandby;
    @JacksonXmlProperty(localName = "LocalGoShow", isAttribute = true)
    protected BigInteger localGoShow;
    @JacksonXmlProperty(localName = "ThruGoShow", isAttribute = true)
    protected BigInteger thruGoShow;
    @JacksonXmlProperty(localName = "LocalPostiveSpace", isAttribute = true)
    protected BigInteger localPostiveSpace;
    @JacksonXmlProperty(localName = "ThruPostiveSpace", isAttribute = true)
    protected BigInteger thruPostiveSpace;

    /**
     * Gets the value of the localRevenueWithReservation property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLocalRevenueWithReservation() {
        return localRevenueWithReservation;
    }

    /**
     * Sets the value of the localRevenueWithReservation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLocalRevenueWithReservation(BigInteger value) {
        this.localRevenueWithReservation = value;
    }

    /**
     * Gets the value of the thruRevenueWithReservation property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getThruRevenueWithReservation() {
        return thruRevenueWithReservation;
    }

    /**
     * Sets the value of the thruRevenueWithReservation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setThruRevenueWithReservation(BigInteger value) {
        this.thruRevenueWithReservation = value;
    }

    /**
     * Gets the value of the localRevenueStandby property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLocalRevenueStandby() {
        return localRevenueStandby;
    }

    /**
     * Sets the value of the localRevenueStandby property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLocalRevenueStandby(BigInteger value) {
        this.localRevenueStandby = value;
    }

    /**
     * Gets the value of the thruRevenueStandby property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getThruRevenueStandby() {
        return thruRevenueStandby;
    }

    /**
     * Sets the value of the thruRevenueStandby property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setThruRevenueStandby(BigInteger value) {
        this.thruRevenueStandby = value;
    }

    /**
     * Gets the value of the localNonRevenueStandby property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLocalNonRevenueStandby() {
        return localNonRevenueStandby;
    }

    /**
     * Sets the value of the localNonRevenueStandby property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLocalNonRevenueStandby(BigInteger value) {
        this.localNonRevenueStandby = value;
    }

    /**
     * Gets the value of the thruNonRevenueStandby property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getThruNonRevenueStandby() {
        return thruNonRevenueStandby;
    }

    /**
     * Sets the value of the thruNonRevenueStandby property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setThruNonRevenueStandby(BigInteger value) {
        this.thruNonRevenueStandby = value;
    }

    /**
     * Gets the value of the localGoShow property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLocalGoShow() {
        return localGoShow;
    }

    /**
     * Sets the value of the localGoShow property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLocalGoShow(BigInteger value) {
        this.localGoShow = value;
    }

    /**
     * Gets the value of the thruGoShow property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getThruGoShow() {
        return thruGoShow;
    }

    /**
     * Sets the value of the thruGoShow property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setThruGoShow(BigInteger value) {
        this.thruGoShow = value;
    }

    /**
     * Gets the value of the localPostiveSpace property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getLocalPostiveSpace() {
        return localPostiveSpace;
    }

    /**
     * Sets the value of the localPostiveSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setLocalPostiveSpace(BigInteger value) {
        this.localPostiveSpace = value;
    }

    /**
     * Gets the value of the thruPostiveSpace property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getThruPostiveSpace() {
        return thruPostiveSpace;
    }

    /**
     * Sets the value of the thruPostiveSpace property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setThruPostiveSpace(BigInteger value) {
        this.thruPostiveSpace = value;
    }

}
